# -*- Makefile -*-

# ------------------------------------------------------------------------
AS        ?= gas
CC        ?= gcc
AR        ?= ar
CFLAGS    ?= -Wall -W -O2
JASMINC   ?= jasminc
EASYCRYPT ?= easycrypt
